### ISSUE TITLE
Install instruction missing

### ISSUE THREAD

**Issue by terxw** [ihdavids/orgextended#1]
Hi,

can you add setup instruction/ how to add this extension to sublime?

**Comment by ihdavids** [comment]
Thank you for the feedback.
There are setup instructions although they are somewhat hidden.

docs > setup.org has information on how to get setup.
There may be items in there that are unclear. I am now quite used to working with this plugin as a repo and may have poorly documented the setup process. 

I am happy to clarify

Hopefully eventually we will get this integrated as a proper sublime plugin and the need for manual cloning will no longer be required,

**Comment by ihdavids** [comment]
I have moved the documentation out of the package itself to help reduce the size of the download if/when this becomes a sublime package.

The documentation can now be found here:
https://github.com/ihdavids/orgextended_docs

**Comment by ihdavids** [comment]
The start.org file should have links to the setup instructions:

Which I think resolves here:
https://github.com/ihdavids/orgextended_docs/blob/master/setup.org
