### ISSUE TITLE
Checkbox summaries not working in headings

### ISSUE THREAD

**Issue by ihdavids** [ihdavids/orgextended#13]
Love this plugin, it has much better user experience for note taking and task managing compare to markdown.
Thank you for bring orgmode to sublime text .

However, I have experienced a small issue, checkbox summary do not work in titles,
e.g. below is my todo list

* TODO [#A] someting [%]
    - [-] work-1 [2/3]
        - [x] a <2021-02-17 Wed>
        - [x] b <2021-02-17 Wed>
        - [ ] c
    - [ ] work-2 [0/1]
        - [ ] 2

* TODO [#A] someting [%] do not show the summarized information properly with "[%]" and "[/]" tag, how can I fix it?

**Comment by ihdavids** [comment]
Caobo reported an issue with checkboxes, I have moved this over here so I don't miss this.
Original: https://github.com/ihdavids/orgextended_docs/issues/4

yup, this is something I should support:
https://orgmode.org/manual/Checkboxes.html

I will add it to my todo list of things to add

**Comment by ihdavids** [comment]
Actually... that was easier than expected. 1.1.7 will have support for this.

**Comment by caobo** [comment]
@ihdavids Wow, thanks a lot. Cannot wait to enjoy this plugin even more.

**Comment by ihdavids** [comment]
1.1.7 is pushed. It should be up in an hour or so.

**Comment by caobo** [comment]
It works perfectly now, thank you a lot.

**Comment by ihdavids** [comment]
Yay.
Glad its working.

**Comment by caobo** [comment]
Thanks for your hard work, recent upgrades are on fire.
And I'd like to propose a minor tweak of checkbox summary in titles.

current checkbox summary in title shows the information of done/total_works of items but not reflects sub-items
e.g. in my todo list it is like:
* Total works[0%]
 - [ ] A [2/3]
     - [x] 1
     - [x] 2
     - [ ] 3
- [ ] B [1/3]
     - [x] 1
     - [ ] 2
     - [ ] 3
after days of work, total work progress remains 0% is a little bit frustrating.

Because it is a personal preference more than an actual issue, so I posted here^_^.

Best regards

**Comment by ihdavids** [comment]
Hmmm. I think org has some options for recursive summaries. Let me investigate.

I am in process of working on formula support for tables. That is going to take a little bit to get checkinable. I will see if I can figure something out and work it in.

**Comment by ihdavids** [comment]
Looks like this can sort of be done in org with the cookie_data property or turned on globally with an option in your config.


* headline [%] 
:PROPERTIES: 
   :COOKIE_DATA: recursive
:END: 

I will experiment with supporting these when I can make time.

**Comment by ihdavids** [comment]
Note these just mean that the top heading counts ALL sub checkboxes regardless of depth. Which isnt exactly what you were saying. I could add a mode specific to your desire but it would be great to know others would want that as well if I am going down the custom option road.

**Comment by caobo** [comment]
It would be great if I can turn it on or off in my configuration file, however, as I said it is minor.
I am already very much satisfied with this wonderful plugin.
Appreciate your responses and brilliant work.

**Comment by ihdavids** [comment]
1.1.19 should have this feature.

**Comment by ihdavids** [comment]
Again it will summarize all checkboxes under a heading as this seems to be what org supports. Going a custom route and only summarizing leaf checkboxes is possible if that is really what you wanted instead of this but it will be a break away from pure org functionality.

 - [-] Testing parent	[3/6]
     - [x] A
     - [-] B
          - [  ] C 
          - [x] 
          - [x] 
     - [ ] F

Not sure why indent is not working here....
AB and F are all at the same indent level while CDE are all under B

**Comment by caobo** [comment]
Thank you, this is exactly what I wanted.

**Comment by ihdavids** [comment]
Wonderful.
I was worried it wouldn't meet your needs.
