### ISSUE TITLE
Many Items Not Showing on Agenda

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [ihdavids/orgextended#14]
I'm not sure if somehow my install has been corrupted by recent activity, but no changes I do now appear on the agenda.
Nothing strange in the console. I'm at a bit of a loss here :/

https://user-images.githubusercontent.com/1378483/108609116-02a7b500-73cc-11eb-8ed7-7b968a8dafc2.mp4

**Comment by ihdavids** [comment]
In your example your time is at 23:00 hours which is outside of your time range.

**Comment by ihdavids** [comment]
Also, I noticed that my definition of a loose task is a little off.
It currently excludes parent tasks with no children. 

(The check is any todo that does not have a parent that is a todo, but excludes top level todos)

IE: This would be a loose todo:
* I am a heading without a todo
** TODO I am a child with a todo

But this is not:
* TODO I a top level heading with a todo.

I have changed that definition to mean any TODO that does not have a parent that is a TODO OR any root level TODO that does not have any children that are TODOs.

**Comment by ihdavids** [comment]
But the time entry is definitely outside of the time range of your agenda (your agenda currently goes to 22:00 and 21:00) so your item at 23:00 doesn't show up in the agenda. That is as designed. The agenda only shows the time range you set it to in your configuration. So if you only care about work hours then it won't show you tasks outside of that. The todo's should still show up in your other todo lists, just not the time views.

**Comment by ihdavids** [comment]
1.1.9 is now pushed, the loose agenda item is fixed in there.
NOTE: I also have a fix for your unsaved file thing. Now, when I pop open the agenda I will recan all open buffers.
