### ISSUE TITLE
"orgFiles" User Setting Not Working

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [ihdavids/orgextended#16]
The user setting orgFiles does not seem to be working.
See attached video

https://user-images.githubusercontent.com/1378483/110151350-a8055480-7de0-11eb-8414-61aa0ede157d.mp4

I tried with a mapped drive too just incase it was the UNC path, and I also tried with escaped backslashes.
Also - I must say fantastic progress lately!

**Comment by ihdavids** [comment]
Heh... how can you tell that you aren't using a feature...

        # TODO: Add back files entry
        #self.orgFiles = sets.Get("orgFiles",None)

Looks like I removed the orgFiles entry a while back. I will fix that. :)

**Comment by ihdavids** [comment]
I am exceptionally glad you are finding the work I am doing beneficial

**Comment by ihdavids** [comment]
This will be fixed in 1.1.21

**Comment by ihdavids** [comment]
1.1.21 is pushed, it has the fix, some really basic support for gnu plot with tables and some BOM handling for utf-16 org files.
Hope this helps. I will look at your other issue and think about what we might do there.
