### ISSUE TITLE
RFE: glob pattern in orgDirs/orgFiles

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [ihdavids/orgextended#17]
I was thinking that it would be really useful to be able to put a glob pattern in the orgDirs or orgFiles settings. We have a lot of projects running simultaneously and they all have essentially the same folder structure. It seems like a really strong use case to use org files to keep track of and present an overview of all projects.

**Comment by ihdavids** [comment]
Can you give me an example of what you mean here?
orgDirs is effectively a glob pattern of *.org under a directory so I am guessing you are looking for something more involved here.

**Comment by Anti-Distinctlyminty** [comment]
Sure. So our folder structure is something like this `T:/[projectId]/Reference/[projectId].org`
So if I could use the pattern `T:/*/Reference/*.org` it would scan the `Reference` directories of all projects.
These directories can be numerous and deep, so I'm thinking of what the best method is to have flexibility and keep the scanning time minimal.

**Comment by ihdavids** [comment]
I will have globbing support like this in 1.1.22
As you said, unless I fire up some threads to do the globbing / parsing this could really slow down your sublime start up times...
We may want to add a deferred mechanism into the parsing of org files or something.

**Comment by ihdavids** [comment]
1.1.22 is now pushed.
It has directory globbing. Please use with caution!

**Comment by Anti-Distinctlyminty** [comment]
Thanks! I just gave it a test and I'm having no luck. With

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 298, in on_api_ready
    plc()
  File "C:\Users\Luke\AppData\Roaming\Sublime Text 3\Installed Packages\OrgExtended.sublime-package\orgextended.py", line 74, in plugin_loaded
    db.Get().RebuildDb()
  File "C:\Users\Luke\AppData\Roaming\Sublime Text 3\Installed Packages\OrgExtended.sublime-package\orgdb.py", line 273, in RebuildDb
    for path in Path(orgPath).glob(suffix):
  File "C:\Users\Luke\AppData\Roaming\SUBLIM~2\Packages\pathlib\all\pathlib.py", line 997, in glob
    for p in selector.select_from(self):
  File "C:\Users\Luke\AppData\Roaming\SUBLIM~2\Packages\pathlib\all\pathlib.py", line 493, in _select_from
    if not is_dir(parent_path):
  File "C:\Users\Luke\AppData\Roaming\SUBLIM~2\Packages\pathlib\all\pathlib.py", line 1188, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "C:\Users\Luke\AppData\Roaming\SUBLIM~2\Packages\pathlib\all\pathlib.py", line 1051, in stat
    return self._accessor.stat(self)
  File "C:\Users\Luke\AppData\Roaming\SUBLIM~2\Packages\pathlib\all\pathlib.py", line 346, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'T:\\*'
```

I looked at the code [here](https://github.com/ihdavids/orgextended/blob/99871529a53c58f13787c5e77ebf50558a0b4228/orgdb.py#L273) and my guess is that the glob pattern is being included in the `Path()`, rather than the `.glob()`. e.g. This raises the same error

```python
from pathlib import Path
p = Path('T:/*')       # Glob *
for path in p.glob('/*'):
	print(path)
```
where as this works

```python
from pathlib import Path
p = Path('T:/')
for path in p.glob('*/*'):
	print(path)
```
I'm not certain though as I'm not debugging the code, just guessing from what I can see.

**Comment by ihdavids** [comment]
Hmmm
Are you using 2 stars?

The code is brittle here. I am splitting it based on the presence of a directory glob with little error handling.

So this should work:

T:\\**\mypath

And this will not:

T:\\*\mypath

I will add better error handling there.

**Comment by ihdavids** [comment]
Note it only supports directory globs. It adds on the file glob itself.

**Comment by ihdavids** [comment]
Try that. (1.1.23)
I now detects T:\\*\\mypath and gives some useful errors about it.
NOTE: this option only works for orgDirs not orgFiles.

**Comment by Anti-Distinctlyminty** [comment]
> Hmmm
> Are you using 2 stars?

No, just a single one which is intentional, as in my case the folder structures are so big that a ** results in Sublime not responding as it's searching every folder on the whole drive.

My folder structure is like this

```
T:/0112/Reference/0112.org
T:/0116/Reference/0116.org
T:/0221/Reference/0221.org
⋮
```
So I only need to * the single folder that changes
`T:/*/Reference`

**Comment by ihdavids** [comment]
1.1.25 may have single folder wildcards like you want

**Comment by Anti-Distinctlyminty** [comment]
Fantastic!
