### ISSUE TITLE
How to set up tab cycling?

### ISSUE THREAD

**Issue by 0xbs0d** [ihdavids/orgextended#2]
Hey,

I added the key binding snippet from your docs to my user keymap in sublime but my tabs aren't folding. Tab isn't doing anything at all after that. Is there anything else I'm supposed to do?

Other than that, this is an amazing extension and I love it. Thank you for you work! :)

**Comment by ihdavids** [comment]
Oh i think that bit of doc is old.
You shouldnt have to so anything anymore for tab cycling. It should work
out of the box.

I will probably remove the mouse map to get it through review an give you a
command to add it back. It is just there to let you click on a date in the
calendar view.


Thanks for the feedback.

Ian

**Comment by 0xbs0d** [comment]
Thank you for getting back at me. I removed the key binding but now the tab key works as a normal tab key. Maybe it's one of my other plugins creating a conflict. I'll try to figure it out.

**Comment by ihdavids** [comment]
Hmmm, the Default.sublime-keymap has all the core keybindings. Perhaps the filetype is not an org file?
Perhaps the package is throwing an exception? Can you check the Ctrl-` panel?

I use custom contexts to determine the appropriate tab handler (for folding a property / link / heading / block etc)
Perhaps something in there is throwing an exception?

**Comment by 0xbs0d** [comment]
I apologize. I'm a moron. I cloned the repo in the packages folder instead of the packages/OrgExtended and obviously it didn't install correctly. I managed to debug everything after I started to check the console. Thank you for your support and once again, tnx for this plugin :)
