### ISSUE TITLE
Daily Journal Feature Request

### ISSUE THREAD

**Issue by olegbc1** [ihdavids/orgextended#27]
Originally requested [here ](https://forum.sublimetext.com/t/org-extended/52036/4) but porting over to GitHub so everything is in one place.

**Abstract:** I like to keep a historical record of my agenda, which means having Org create a new daily note for me in a predefined folder, with a predefined filename (usually just date e.g., `2021-03-31.org`). Org would then add all of the tasks which aren't marked complete to the newly created note. Daily note files from previous days (containing crossed-off tasks) can then be moved to an archive (another predefined folder).

**References:** different, but similar feature is described and implemented [here](https://almostobsolete.net/daypage.html) via [org-daypage](https://github.com/almost/org-daypage/blob/master/org-daypage.el) package for emacs. There is also [org-journal](https://www.emacswiki.org/emacs/OrgJournal) package ([github](https://github.com/bastibe/org-journal)) that may be worth checking out.

**Comment by olegbc1** [comment]
Some relevant information for implementation provided by the original author of the plugin @ihdavids on [Sublime forums](https://forum.sublimetext.com/t/org-extended/52036/7). 

----------------------------

`orgagenda.py` is probably where you want to start for an example of walking the DB to get the details of the day.
Each of the panels (separated by ===============) are independent “View” objects that each get access to the org file DB, get to filter the results they care about and produce a “Render” of what they have filtered.



Then you probably want to look at `orgcapture.py` which has` OrgArchiveSubtreeCommand` which is a text command that can archive a subtree. It’s… quite a hack, but should give you enough to build your own. NOTE: Because I have chained editing of a buffer going on in there (adding property drawers and adding properties for the archived element) you are going to run smack dab into one of the little goofy things I did which is use `pymitter` and an `onDone` token to allow me to chain sublime textcommands (Execute one text command after another, once it executes) Where I can’t do that (like running the sublime “save” command) I cheat and use a timer to run after the command has executed. Like I said… it’s an ugly little hack. Sadly the capture code was probably one of the first things I wrote, so it is probably one of the worst offenders of some of those hacks as I learned better ways to handle some of that stuff later on.

Finally, you either will want to tie into the notifications thread if you are trying to do this automatically, OR have your text command bound to the agenda? For that I use independent syntaxes… That is a major hack I do to allow me to have independent coloring of the buffer (based on an independent syntax) and independent key bindings, like the agenda where enter will open the item and space will open it in a new window. You can see the agenda bindings in `Default.sublime-keymap.`

**Comment by ihdavids** [comment]
Questions:

1) Is this exactly like day-page package or is this different? You kind of say it is different so I assume so.
2) Is there a key binding for creating this day page? Or is this done automatically some time?
2a) Is there auto tagging / filetags of these tasks? Is there any structure to the day page itself? Do tasks in the day page automatically all get added to the today date in the agenda or are they all manually scheduled?
3) It sounds like tasks targeting today are copied to the today page? Or are they moved?
4) Is it just tasks targeting today or is it all open tasks?
5) So this would leave closed tasks behind in old day pages then?
6) Archiving, would this follow regular archiving rules or would this be a special second class archiving mechanism?
7) How do these tasks get archived? Under some heading? Root level tasks? How do we handle tasks inside projects that are not entirely complete?
8) Do archived tasks add properties to the archived tasks?
9) Agenda, adding these files to the agenda... Is this done implicitly for you are are you responsible for adding it to orgDirs


----------------------------------------------

This feels like a slightly bigger project. Is there a progression at which we could roll this out so it would be useful and usable along the way to work out any kinks?

**Comment by ihdavids** [comment]
1.2.8 just got pushed.

I added a Org Day Page Create command. It's NOT the feature... but it's a tiny step in this direction. :)

**Comment by ihdavids** [comment]
olegbc1
Were you able to answer any of the questions above?

**Comment by olegbc1** [comment]
Just to reopen the feature request as I am resurfacing for some air from work. With regards to the questions asked, I would just keep the feature very simple and just make it in form of an option which, when enabled, would trigger each time a new daily note is create, and would copy the contents of the prior daily note, except for the todos marked done into the new one. <- this would be the experience, in reality the plugin could archive the completed tasks and move the non-completed to the new note. Perhaps leaving a tag of some sort for traceability. Thoughts?
