### ISSUE TITLE
"Org Create Color Scheme From Active" error

### ISSUE THREAD

**Issue by smithx** [ihdavids/orgextended#29]
I'm trying to make color scheme by "Org Create Color Scheme From Active" command (as described in docs) and get error in console:
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 1494, in run_
    return self.run(edit)
  File "C:\Users\user\AppData\Roaming\Sublime Text\Installed Packages\OrgExtended.sublime-package\orginternalhelpers.py", line 684, in run
  File "./python3.3/ast.py", line 47, in literal_eval
  File "./python3.3/ast.py", line 35, in parse
  File "<unknown>", line 533
    // Sublime Merge
     ^
SyntaxError: invalid syntax
```
ST  4101
orgextended 1.2.13

**Comment by ihdavids** [comment]
Hmmm
I am going to need the name of the colour scheme you have set. Looks like it has some stuff I need to strip that is causing the parser to fail.

**Comment by ihdavids** [comment]
I will beef that up so it reports that as well for the next time we run into something like this as well.

**Comment by smithx** [comment]
I use Solarized (Dark) color scheme and Adaptive theme

**Comment by ihdavids** [comment]
Awesome.
I will try to go duplicate this and see if I can harden the generator. It has only ever been used against my personal color scheme choices so... ;)

**Comment by ihdavids** [comment]
Yup, I am able to duplicate. I will see if I can work on this tonight.

**Comment by ihdavids** [comment]
Yup, It has comments in the yaml and the parser is complaining. 
I think I have a fix. It should go out tonight.

**Comment by ihdavids** [comment]
Should be fixed in 1.2.14.

**Comment by ihdavids** [comment]
NOTE: the system will generate a color scheme from your active scheme. It however will try to use "standard" tags like function, class etc for various headings. 

If you find you want to tweak it there are a bunch of comments in the generated scheme and the files are found in Packages\User\OrgColorSchemes\<name>.sublime-color-scheme

**Comment by smithx** [comment]
Thank you, everything works fine
