### ISSUE TITLE
Autocompletion for insert local file

### ISSUE THREAD

**Issue by waynezhang** [ihdavids/orgextended#30]
This is a great extension! Thanks a lot!
Just wondering is there any easy way to insert a link to local file (kinda like orgroam)?

**Comment by ihdavids** [comment]
Hi!
Glad you are enjoying it.
I have not used org roam, so I am not sure exactly what you are referring to.

Yes it does try (although not perfectly yet) try to support intra file links to ids, headings, named blocks etc.

There are some commands for creating links from your caret on a heading.

There is a snippet for quick link creation.

I don't have auto complete support for cross file link creation, although that sounds quite doable given what we have to work with.

Can you help me understand the feature better?

**Comment by ihdavids** [comment]
Honestly backlinks are probably fairly easy to generate from your orgdir during the parse phase, the harder part to support in sublime is the visualization of those links. Emacs buffer and window management and narrowing make that much easier.

**Comment by ihdavids** [comment]
That said, i probably won't try to build the roam server for the moment but there is no reason for me not to put the link management and backlink view on my roadmap. Not sure when I would get to it unless someone wants to join me in this effort but it looks useful.

**Comment by waynezhang** [comment]
Thanks for the quick response!

I just feel that it's a little hard to input the file path manually and very easy to make mistakes.
I'm a newbie of org-mode and org-roam but I found the searching local file by TITLE and inserting the link automatically feature very useful.

**Comment by ihdavids** [comment]
It is definetly on the list. I have been using org roam now and its very slick. Better than org wiki.

We will see when I can get to some of this.

**Comment by ihdavids** [comment]
I am currently mid effort on a latex exporter. Once I need a break from that I will see about doing some of this.

**Comment by waynezhang** [comment]
> It is definetly on the list. I have been using org roam now and its very slick. Better than org wiki.
> 
> We will see when I can get to some of this.

Great!

**Comment by ihdavids** [comment]
Thank you for contributing as well. This is great

**Comment by ihdavids** [comment]
I may move the feature into asettings.py so we can use that for the paths to tools like node and other interpreters if you have done a local install. Its a good idea.

**Comment by ihdavids** [comment]
1.2.21 Has a text command that will show a quick panel with files from your orgDirs

ALSO: Autocomplete has been turned on now and inside [[ It will try to give you a list of files to work with. the autocompletion system in ST3 is challenging. ST4 dynamic autocompletion should work better, we will see as it matures.

**Comment by waynezhang** [comment]
> 1.2.21 Has a text command that will show a quick panel with files from your orgDirs
> 
> ALSO: Autocomplete has been turned on now and inside [[ It will try to give you a list of files to work with. the autocompletion system in ST3 is challenging. ST4 dynamic autocompletion should work better, we will see as it matures.

Wow! That's great. IMO It will better to insert the link as a relative path rather than an absolute path. I'll also take a look at this when I get time.
BTW, do you have any plan to apply PEP8 rules? I can submit a PR  for this later maybe.

**Comment by ihdavids** [comment]
Hmm,
I am not a fan of autoformatting and I also tend to work on wide screen monitors and use golden ratio mode so I dont have a problem with long lines.

I think I will avoid pep8.

**Comment by waynezhang** [comment]
I see.

**Comment by ihdavids** [comment]
Back references is still on the backlog as well as some of the other roam fun. We will see when there might be time to look into some of that.

At the moment the files are full paths. I took the expedient root for the moment. Feel free to tweek that if relative paths are important.

**Comment by waynezhang** [comment]
I use multiple machines with different user accounts so it's kind of necessary to me. I will take a look at it later.

**Comment by ihdavids** [comment]
Makes sense.

**Comment by ihdavids** [comment]
Happy for you to clean that up.
Heck, I cheated and just bolted the autocomplete functionality onto the table ViewEventListener so I could get something out tonight. :) I need to go back and generalize that piece. I think I have 2 ViewEventListeners now and I only need 1, so I have a bit of cleanup to do there.

Sooo many things I want to implement and so little time. :)

**Comment by waynezhang** [comment]
Currently, the new code inserts `(tag) TITLE` as link description. Is that on purpose? Or is it OK to change to `TITLE`? I personally prefer the latter one.

**Comment by ihdavids** [comment]
Yeah, trying at least work towards mimicing org roam.
Roam has its own file tags that if present end up in the description when searching.

You can make that configurable if you want.
sets.Get("setting", default) will pull the setting out of the OrgExtended.sublime-settings file.

**Comment by ihdavids** [comment]
That seems like a good thing to make open to personal prefefence.

**Comment by ihdavids** [comment]
Feel free to join the group on discord if you want.

https://discord.gg/DW2kDDm2

Just a place to chat about the plugin with those interested in contributing
