### ISSUE TITLE
Regex Failure with Colon in Title

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [ihdavids/orgextended#38]
I was trying to insert a tag on a heading looking something like this

```
* 0:15 something
```
I often use timecodes in headers. I'm guessing that the colon is confusing the regex (I tried to look for the regex but couldn't find it).
If it's not a trivial fix, just close this and I'll have to not use colons in headers :)

**Comment by ihdavids** [comment]
Yeah. That one was a known issue I havent taken the time to work out. Its in the syntax file and the tag system.

I dont use colons in my headings so I havent really cared about it. That said, you do so I will make an attempt when I can.

**Comment by ihdavids** [comment]
Sorry I haven't gotten to this yet.

**Comment by ihdavids** [comment]
1.2.32 is being pushed today and the fix didn't make it into that but I have a fix for this now and it should be in 1.2.33.

**Comment by ihdavids** [comment]
1.2.33 is pushed and should have this fix
