### ISSUE TITLE
Agenda week view settings

### ISSUE THREAD

**Issue by smithx** [ihdavids/orgextended#4]
We have settings  "agendaDayStartTime" & "agendaDayEndTime" for day view.  Can ones be applicable to week view to hide usually empty hours. (or its must be another settings i.e. agendaWeekStartTime" & "agendaWeekEndTime ?)
![image](https://user-images.githubusercontent.com/2234320/106491868-5c514980-64c8-11eb-82c6-d895bdd9c5c2.png)

**Comment by ihdavids** [comment]
Hmmm, yeah, I can make that change.

**Comment by ihdavids** [comment]
The agenda is a very personal thing in OrgMode and I haven't quite thought of a good way (other than the views systems I created and hopefully the eventual capability to write their own custom views in the User folder) to give people ways of  customizing this stuff.

I am hoping at some point I can create a tool to build a color scheme (using your personal color sheme) for the agena dynamically. But for now, thank you for these suggestions and keep them coming. I am happy to add features like this where I can make time.

**Comment by ihdavids** [comment]
1.0.3 now respects agendaDayStartTime and agendaDayEndTime in the week view
