### ISSUE TITLE
Changing todo state leaves previous state in heading

### ISSUE THREAD

**Issue by stevenkaras** [ihdavids/orgextended#40]
When I use the "Org Change Todo" command, it leaves the previous TODO state in the heading.
For example, from this:

```orgmode
* TODO example heading
  this is some content inside the heading
```

Then invoking the "Org Change Todo" command from the command palette and selecting "DONE" used to result in this:

```orgmode
* DONE example heading
  this is some content inside the heading
```

but recently began behaving as such:

```orgmode
* DONE TODO example heading
  this is some content inside the heading
```

**Comment by ihdavids** [comment]
Hmmm
I suspect this is throwing mid update. Which would account for it leaving the old text. Can you grab your sublime console output after trying one of these operations? 

Ctrl-~ to bring up the console. Copy the output and paste here. 

I will instruct you how to turn on tracing next so we can get a bit more output out next but first lets start with the assumption this is an exception somewhere.

I am not able to duplicate this locally

**Comment by ihdavids** [comment]
Any more detail as I mentioned above? I cannot duplicate this in my local files at the moment.

**Comment by stevenkaras** [comment]
There is no error logged to the console. Interestingly, this only happens with the transition from TODO, not the other way around. The TODO state is also marked with a tag "(!)" for some reason, but I don't think I have any settings that would affect that.

I'll try adding some extra logging if you could point me to the relevant files/functions.

**Comment by ihdavids** [comment]
Hmmm. Well, this particular command was written before I had to much logging in place, so I don't have any log.debug()'s in there to really trace what is going on. Drat.

You can follow the instructions here: https://github.com/ihdavids/orgextended_docs/blob/master/manual_install.org
and pull the repo and add some logging.

I have 2 ways to turn on logging:
The first is an environment variable: SUBLIME_ORGEXTENDED_DEBUG and the other is a setting in your org extended settings file: enableDebugLogging. Either of those will get some debug spew being generated for the plugin. But I don't think that is going to help in this case.

I don't have support for annotations on todo transitions yet. That is something I want at some point. I have the start of some of that (CLOSED for instance) but not all of it. IE: (!) - which means put a timestamp when you transition to this. Here is an example of what I get at the moment:

![todo_transitions_are_working](https://user-images.githubusercontent.com/1059210/119091362-caf7db80-b9c1-11eb-9261-44f1bd9b98a4.gif)

**Comment by ihdavids** [comment]
The code in question for this can be found in orgediting.py:

![image](https://user-images.githubusercontent.com/1059210/119091853-8587de00-b9c2-11eb-9fb9-ec5ffaed3e6b.png)

The text command will fire up the quick panel and then call on_done where it tries to replace the text.

**Comment by ihdavids** [comment]
I am afraid I have no idea how to help you other than marking up the command for the next release and then hoping we catch something with debug logging turned on as I have no idea how to duplicate your situation. You will need to see if you can help me figure out how to duplicate your scenario.

**Comment by stevenkaras** [comment]
It wasn't happening on my personal laptop so this took a while for me to get around to. I upgraded to ST4 in the meantime and the issue went away.

I'm trying to read through the code and debug it from the console, but hitting some issues around importing dateutil. My current guess is that it's picking up the list of todo states including a priority tag for some reason (probably a faulty regex) and then persisting the problem through multiple invocations.

**Comment by stevenkaras** [comment]
Ok. here's my guess: the default todo states as defined in [asettings.py](https://github.com/ihdavids/orgextended/blob/b7d852fd79002a8d38c7c1a2e77bd2a9ff252a99/asettings.py#L12) are:

```python
defaultTodoStates = ["TODO(!)", "NEXT", "BLOCKED","WAITING","|", "CANCELLED", "DONE","MEETING","PHONE","NOTE"]
```

Which is only used if the application settings can't be loaded, which are set in [OrgExtended.sublime-settings](https://github.com/ihdavids/orgextended/blob/b7d852fd79002a8d38c7c1a2e77bd2a9ff252a99/OrgExtended.sublime-settings#L219) to:

```json
    "todoStates": ["TODO","NEXT", "BLOCKED","WAITING","|", "CANCELLED", "DONE","MEETING","PHONE","NOTE"],
```

So I'm guessing that at some point the settings weren't available for some reason (this could be anything from a random hiccup to a temporary quarantine by the corporate endpoint protection that segfaults multiple times a day), it fell back on the defaults set in the code and the rest is history.

**Comment by ihdavids** [comment]
Ah, I see.
That makes sense since I don't strip off the markers in the settings file yet as I don't really have support for those custom transitions. I only actually strip the states when they are embedded in the file to try to ensure people that have existing org files with those transitions in them don't blow up. 

Hopefully someday soon I will support those transitions.
For now I have fixed that string in asettings.py.

Thanks for helping to track it down.

**Comment by ihdavids** [comment]
The offending line should be removed in 1.2.33
