### ISSUE TITLE
Slow checkboxes

### ISSUE THREAD

**Issue by Sinamore** [ihdavids/orgextended#42]
Toggling a checkbox works very slow for me in a particular case:

I have a document with ~150 checkbox summaries, each of them has 5-10 subitems. When I toggle checkbox in a subitem, recalculation of all summaries is done. I suppose it's enough to recalculate only affected ones.

I've made a fix for this problem: https://github.com/Sinamore/orgextended/tree/slow-checkboxes

Please, have a look at it, and tell if it's good enough to make it as a PR.

**Comment by ihdavids** [comment]
Sure

Make a PR for it and I will pull it and test it out.
Thanks for hacking on that.
