### ISSUE TITLE
Checboxes do not toggle

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [ihdavids/orgextended#44]
**Describe the bug**
Checboxes to not toggle

**To Reproduce**
1. Make sure the toggle checkbox command is added to the keymap
`{ "keys": ["enter"],             "command": "orgmode_toggle_checkbox",         "context": [{ "key": "selector", "operator": "equal", "operand": "orgmode.checkbox" }]}`
2. Create an item with a checkbox
   ```
    * List
      - [ ] Blah
   ```
3. With the cursor inside the checbox, hit enter
4. Nothing happens

**Expected behavior**
The checkbox should toggle

**Screenshots**

**Platform:**
- Windows 10, Sublime Text  Build 4107

**Sublime debug console output**
Nothing is output.

**Comment by Sinamore** [comment]
Will it toggle if you add the toggle command to `Default (Windows).sublime-keymap` file?

**Comment by Anti-Distinctlyminty** [comment]
I cannot edit that file

**Comment by Sinamore** [comment]
I rechecked the repo state, there is no `Default (Windows).sublime-keymap` file, you should create it yourself. Can you create it? (It should be next to `Default.sublime-keymap` in orgextended's root)

I did this on my Linux machine (`Default (Linux).sublime-keymap` in my case) to make the checkboxes toggle.

**Comment by Anti-Distinctlyminty** [comment]
Apologies, I had already done this, and it does not work. Here is my Default (Windows).sublime-keymap
```json
[
    { "keys": ["ctrl+shift+`"], "command": "show_panel", "args": {"panel": "console", "toggle": true} },
    { "keys": ["alt+o", "i", "g"],       "command": "org_insert_tag",                "context": [{ "key": "eol_selector", "operand": "text.orgmode"}] },
    { "keys": ["enter"],             "command": "orgmode_toggle_checkbox",         "context": [{ "key": "selector", "operator": "equal", "operand": "orgmode.checkbox" }]}
]
```

**Comment by ihdavids** [comment]
The default should work even without the Default (Windows) file.
I suspect it was a recent PR that may be causing this. I will dig into it as soon as I can make time.

Sorry I have been out for a while.

**Comment by ihdavids** [comment]
Make sure you open the console and give me the console output when you do this.
For instance:

Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1494, in run_
    return self.run(edit)
  File "/home/ian/.config/sublime-text/Installed Packages/OrgExtended.sublime-package/orgcheckbox.py", line 428, in run
  File "/home/ian/.config/sublime-text/Installed Packages/OrgExtended.sublime-package/orgcheckbox.py", line 265, in toggle_checkbox
  File "/home/ian/.config/sublime-text/Installed Packages/OrgExtended.sublime-package/orgcheckbox.py", line 203, in update_line
  File "/home/ian/.config/sublime-text/Installed Packages/OrgExtended.sublime-package/orgcheckbox.py", line 184, in recalc_summary
AttributeError: 'OrgRootNode' object has no attribute 'properties'
Unable to open /home/ian/.config/sublime-text/Packages/Default/Default (Linux).sublime-keymap
Unable to open /home/ian/.config/sublime-text/Packages/User/Default (Linux).sublime-keymap

**Comment by ihdavids** [comment]
The function in question is called org_toggle_checkbox not orgmode_toggle_checkbox.
Change your keybinding to org_toggle_checkbox and it should work.

**Comment by ihdavids** [comment]
Note: Alt-o t should have still worked. That is the dwim toggle method.

**Comment by Anti-Distinctlyminty** [comment]
> The function in question is called org_toggle_checkbox not orgmode_toggle_checkbox.
> Change your keybinding to org_toggle_checkbox and it should work.

This did it, thanks!
I'm not sure if it was me that messed up or not, as usually I just copy from existing key bindings :/
