### ISSUE TITLE
Highlighting for R codes fails 

### ISSUE THREAD

**Issue by AlfredSAM** [ihdavids/orgextended#45]
In the code block, the highlighting for R codes fail in the .org file:

<img width="899" alt="Screenshot 2021-07-09 at 9 02 07 PM" src="https://user-images.githubusercontent.com/47268796/125081748-ed23f500-e0f8-11eb-8a44-372d3658ed2d.png">

On the other hand, in .md file, the highlighting for R codes is fine:

<img width="914" alt="Screenshot 2021-07-09 at 9 03 34 PM" src="https://user-images.githubusercontent.com/47268796/125081893-20ff1a80-e0f9-11eb-9aa2-642ff1da8787.png">

Any advice?

I use MacOS Big Sur 11.4 and ST4 (4107)

**Comment by ihdavids** [comment]
odd
r is in the languagelist.yaml, It should be supported, there may be something wrong with the regex. I will take a look when I can make time.

I have actually been working on a linux box of late so have just been using emacs for my orgmode support and thus have not been actively working on this.

The community use of the project was a little lackluster which was a bit surprising to me, so I have not been investing in things that I don't need.

**Comment by ihdavids** [comment]
Interesting, can you type Ctrl-Alt-Shift-P I suspect you will see the block is trying to set the context to source.r(\s|$) vs source.r, looks like I didn't supply the language target for the regex and so the generated match is just wrong.

I will try to fix when I can.

**Comment by AlfredSAM** [comment]
I see. Well, I think it is a great project. I use sublime text for projects, but I came across org mode from the coworkers who love Emacs so much. I like the org mode for notes, and so exited to meet your plugin used in sublime text. 

Please just take your time, and thanks so much for your great works!

**Comment by ihdavids** [comment]
1.2.34 should fix this. Going out today.
