### ISSUE TITLE
File outside orgDirs pulled into Agenda

### ISSUE THREAD

**Issue by schultzter** [ihdavids/orgextended#49]
**Describe the bug**
I've defined my orgDirs to the location where I keep all my org files, but in the Agenda view I see TODOs from another file outside that directory. 

**To Reproduce**
1. Create a file testing.org in C:\Users\user.name\Documents with some TODO's
2. Configure orgextended to look only in C:\Users\user.name\Documents\Projects
3. Create some org files in Projects sub-directory with TODO's
4. Open the Agenda view
5. See TODO from testing.org !?

**Expected behavior**
The files outside the orgDirs are ignored

**Platform:**
Windows SublimeText 4

**Additional context**
// OrgExtended Settings - User
{
	"orgDirs": [
        "C:\\Users\\user.name\\Documents\\Projects"
    ],
    "refile": "C:\\Users\\user.name\\Documents\\Projects\\refile.org",
}

**Comment by ihdavids** [comment]
Yup, this is how it was originally designed. Anything loaded and anything parsed in the background will be visible. 
That said. I think you are right and I should filter out stuff not in the orgDir.

**Comment by ihdavids** [comment]
1.2.34 should have a first stab at this. Can't guarantee it will be perfect
