### ISSUE TITLE
Light color scheme error

### ISSUE THREAD

**Issue by shaund** [ihdavids/orgextended#5]
First, really nice package. Best desktop org-mode implementation I've seen outside of emacs.

I get an error loading the light color scheme on Sublime 3.2.2 build 3211. It says can't find "Packages/OrgExtended/OrgExtended-light.sublime-color-scheme"

I'm using the portable version of Sublime.

**Comment by ihdavids** [comment]
I am glad you are finding the package useful.
I bet there is a case / typo in the name. Sublime is sensitive to the case of the color scheme.

I havent used the light scheme in a while. I will take a look as soon as I can.

On the horizon for me is rejiggering the system to play nicer and work with your existing colour scheme. But thats a bunch of work and I have not made the time for that yet.

**Comment by ihdavids** [comment]
Yeah from the error message it looks like the Light vs light matters.

**Comment by shaund** [comment]
Yep, that was it,. Thanks. It's in lowercase here https://github.com/ihdavids/orgextended_docs/blob/master/setup.org

**Comment by ihdavids** [comment]
Thanks!
I fixed the typo in the docs.
