### ISSUE TITLE
SourceBlockHandlers User Settings

### ISSUE THREAD

**Issue by radeksalomon** [ihdavids/orgextended#50]
**Describe the bug**
I am not able to set another SourceBlockhandler. If I change the settings to:
```
"builtinSourceBlockHandlers": ["plantuml", "graphviz", "ditaa", "mermaid", "powershell", "python", "gnuplot", "cmd", "sh", "javascript", "perl"],
    // These are source block aliases for languages listed in the builtinSourceBlockHandlers
    "builtinSourceBlockAliases": {
        "bash":  "sh",
        "bat":   "cmd",
        "js":    "javascript",
        "conf":  "sh"
    },
```

Sublime ignores the `conf` option. 

**Platform:**
- Macbook Pro Big Sur Sublime 4113

**Comment by ihdavids** [comment]
I probably should update the comment. Syntax highlighting will not pick up the block by just adding to that table. You have to extend the grammer
