### ISSUE TITLE
Emphasis on whole word only

### ISSUE THREAD

**Issue by mirmalag** [ihdavids/orgextended#51]
Please implement emphasis only on whole words, otherwise it's really annoying.
Example:
THIS_IS_AN_ERROR_MESSAGE
results in "IS" and "ERROR" being underlined
Or:
speaking of variable MY_VARIABLE and YOUR_VARIABLE
results in "VARIABLE and YOUR" being underlined.

This is well explained here: https://lists.gnu.org/archive/html/emacs-orgmode/2009-08/msg00091.html

Thank you,
Mirco

PS: Anyway, it's so good having orgmode in sublime. I even think it should be native or fully integrated, like in emacs

**Comment by ihdavids** [comment]
A fix for this should be in 1.2.35.

**Comment by mirmalag** [comment]
Would be great, thank you

**Comment by ihdavids** [comment]
Should be live

**Comment by mirmalag** [comment]
That's it. Thanks a lot.
