### ISSUE TITLE
Are you back? 

### ISSUE THREAD

**Issue by olegbc1** [ihdavids/orgextended#53]
@ihdavids just checking in to see if you're back as I noticed recent commits? Shall we get back to our discord to get collaborating again?

**Comment by ihdavids** [comment]
I am indeed working on things, i dont have massive amounts of time, but i have been adding things i need and fixing a few things.

**Comment by ihdavids** [comment]
1.2.35 went out a bit ago with some formatting fixes and 1.2.36 went out today with some improvements to the datepicker i have wanted for a while.

**Comment by olegbc1** [comment]
Sounds great! Would you be up for getting together to discuss anything we'd want to implement next?

**Comment by olegbc1** [comment]
We can also do this over GH discussions asynchronously

**Comment by ihdavids** [comment]
What did you have in mind?

**Comment by ihdavids** [comment]
I am happy to meet and chat about the plugin, but it might make sense to chat over discord about what you are hoping to see, help with, etc.
