### ISSUE TITLE
Please do add orgextended to the Orgdown tool collection page

### ISSUE THREAD

**Issue by novoid** [ihdavids/orgextended#54]
Hi,

You may have heard of my latest initiative at EmacsConf21 which tries
to **strengthen the non-Emacs support for Org-mode synta**x: 
https://karl-voit.at/2021/11/27/orgdown/ or 
https://tube.graz.social/w/bgJVfjPLQAoJwLJQZoo3Hu (12min video)

According to my initiative, "Orgdown" should be used as a new name for
the Org-mode syntax. This way, we do get a clear distinction between
the GNU/Emacs implementation of Org-mode and its lightweight markup
language syntax. In my opinion, not every tool that supports Orgdown
needs to support the whole set of Org-mode features in order to be a
good choice for users.

At the moment, there is one basic Orgdown level defined: Orgdown1
https://gitlab.com/publicvoit/orgdown/-/blob/master/doc/Orgdown-Levels.org
That basic level is very easy to reach for any tool supporting Orgdown
syntax.

Independent from my approach to introduce a new name Orgdown for the
syntax of Org-mode, the Orgdown project does maintain a collection of
tools with decent Org-mode syntax support on:
https://gitlab.com/publicvoit/orgdown/-/blob/master/doc/Tool-Support.org

So far, I collected many tools on the tool page itself. For a small
subset, I also wrote a detailed tool-support page such as:
https://gitlab.com/publicvoit/orgdown/-/blob/master/doc/tools/GitLab.org

**I would like to invite you to contribute a detailed tool-support page**
as well. The necessary steps to fill out the provided template are
described on:
https://gitlab.com/publicvoit/orgdown/-/blob/master/doc/faq/how-to-add-tools.org

If you do have some questions or feedback, please do not hesitate and
write me an email or add a GitLab issue.

Thank you very much and have a nice day!

**Comment by ihdavids** [comment]
Sure.
OrgExtended is the older sublime org mode..i started hacking on it adding more syntax and just didnt stop.

Now it has agenda
Date picker
Todo lists
An export engine
Table support with formulas
Babel support for a number of languages with tables and lists as inputs as well as quite a few graphing formats like graphviz, mermaid, plantuml etc etc
Capturing, refiling, archiving
Basic org roam backlinks
Folding, startup comments
Dynamic blocks
Clocking and clock reports
Inline images.

**Comment by ihdavids** [comment]
Sorry I am not going to get to this it seems. 
I think based on the OD1 page it's pretty close to 100% support

The OD1 support is mostly visual though. OrgExtended is more about the functionality.
It has agenda's, todos, date insert, table formula, babel, etc ad nauseum, which most editors do not have.

**Comment by novoid** [comment]
Orgdown's only focus is the syntax. There is no functionality. It's a new name/branding for the syntax of Org-mode syntax elements so that we do not have a naming conflict in so many discussions any more.

Having a corresponding comparison on Org-mode Elisp functionality would be peachy as well, I agree. However, that's not the scope of Orgdown and its list of tools that support Org-mode syntax elements.

If your tool has a good syntax match, it would be very cool to have it listed so that people may find it. Although the phrase "Orgdown" did not have a large impact so far, the tool-support page is well-linked and well-used just to find tools that can deal with files in Orgdown format.
