### ISSUE TITLE
Default programs for links

### ISSUE THREAD

**Issue by taylorh140** [ihdavids/orgextended#55]
**Describe the bug**
Links will open in sublime even when that is not an appropriate program.

**To Reproduce**
1. Create word document
2. Generate link in org mode
3. Open link using enter
4. Binary version of word document is presented

**Expected behavior**
Documents with extensions X should open using the system default program.

**Screenshots**
None

**Platform:**
- Win 11 x64

** Sublime debug console output**
-- None

**Additional context**
-- None

**Comment by ihdavids** [comment]
You are welcome to submit a PR. The link implementation leaves a lot to be desired, it is however extensible.
