### ISSUE TITLE
Capture fails silently with unicode error

### ISSUE THREAD

**Issue by Schroedi** [ihdavids/orgextended#57]
**Describe the bug**
Captures with unicode chars are not saved.

**To Reproduce**
Start a capture, paste the following as content:

`don’t`

**Expected behavior**
New entry should appear in the refile file.

**Platform:**
Mac OS 11.6.2, M1
Sublime Text Stable, 4126

** Sublime debug console output**
> Traceback (most recent call last):
>   File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 948, in on_deactivated
>     run_view_callbacks('on_deactivated', view_id)
>   File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 708, in run_view_callbacks
>     callback(v, *args)
>   File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 152, in profiler
>     return event_handler(*args)
>   File "/Users/ascadian/Library/Application Support/Sublime Text/Installed Packages/OrgExtended.sublime-package/orgextended.py", line 113, in on_deactivated
>     capture.onDeactivated(view)
>   File "/Users/ascadian/Library/Application Support/Sublime Text/Installed Packages/OrgExtended.sublime-package/orgcapture.py", line 232, in onDeactivated
>     f.write(str(item))
> UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 72: ordinal not in range(128)

**Comment by ihdavids** [comment]
Interesting. I will try to take a look when I can. I obviously don't personally capture anything with Unicode in it. :)
If you have a fix feel free to submit a PR and I will take a look.

**Comment by ihdavids** [comment]
Yeah, looks like I was not doing anything useful with anything non ascii when writing out the converted file:

        f = open(capturePath,"w+")
        # reauthor the ENTIRE file.
        # This can get expensive!
        for item in captureFileRoot:
            f.write(str(item))
        f.close()
        
        
I will hopefully get a fix in for the next release.

**Comment by ihdavids** [comment]
Okay, a fix for this will be in the 1.2.44 release once I get it ready, there are a few things waiting on me to finish to get it out.
You can work around this by using a direct capture mode template. That will do the capture by opening the file itself and inserting the capture template in place. This of course means that the capture is a little more disruptive but it's using sublimes file functions to save the file.

Here is an example:

        {
            "name": "Todo",
            "type": "entry",
            "target": ["file","D:\\notes\\inbox.org"],
            "snippet": "todo_start",
            "openas": "direct",
            "properties": [],
        },
