### ISSUE TITLE
Cannot call recursive function in source block

### ISSUE THREAD

**Issue by zhouer** [ihdavids/orgextended#58]
**Describe the bug**

Cannot call recursive function in source block

**To Reproduce**

```python
#+BEGIN_SRC python
    def fib(n):
        if n <= 1:
            return 1
        return fib(n - 1) + fib(n - 2)

    def g(n):
        return n * 2

    def f(n):
        return g(n) * 2

    print(f(10))
#+END_SRC
```
cannot call `f(10)` or `fib(10)` correctly, but `g(10)` works fine.

**Expected behavior**

execute recursive function correctly.

**Screenshots**

https://imgur.com/a/l0v1LEy

**Platform:**

sublime text 4 stable channel, build 4126 on ubuntu 21.10

**Sublime debug console output**

```
Your source file has unsaved changes. We cannot run source modifications without saving the buffer.
```

**Additional context**

**Comment by zhouer** [comment]
@ihdavids I think the reason is the user python code are wrap in `def OrgExtendedPythonWrapperFunction`, may I know what's the rationale doing so?

**Comment by ihdavids** [comment]
Yes that would be why.
I wrapped it up in the wrapper for a number of reasons. 

Consider it a limit of the current implementation for the moment.
