### ISSUE TITLE
Moving Heading to Top Erases File Contents

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [ihdavids/orgextended#6]
To reproduce:

1. Create a new org file
2. Add one heading
3. Add a second heading on the same level
4. Use 'alt+o, up' to move the item up
5. The file ask to be reloaded, and it will be blank

See the attached video for this in action
https://user-images.githubusercontent.com/1378483/107825440-66eec700-6d83-11eb-9bda-34566599682b.mp4

**Comment by ihdavids** [comment]
Huh, that's definitely a bug. 
Thanks for finding this. I will add this to the list of things to patch up.

**Comment by ihdavids** [comment]
Fixed in 1.0.8 which has just been pushed
