### ISSUE TITLE
Checkbox coloring not working as expected

### ISSUE THREAD

**Issue by jeffrey-hicks** [ihdavids/orgextended#60]
Preface - this is my first bug report so please let me know if I'm doing something wrong.

**Describe the bug**
The syntax coloring is not working properly for the checkboxes.

**To Reproduce**
Using ST4 (probably the reason), just make checkboxes

**Expected behavior**
Coloration should change based on contents [x] green, [-] red, [ ] tan.

**Screenshots**
![orgextended-syntax](https://user-images.githubusercontent.com/95231534/164534943-d32fcdd4-1956-422a-90d8-6e2303ef84c3.png)
![modified_syntax](https://user-images.githubusercontent.com/95231534/164534949-5e7d9396-7b27-47de-b112-b935e98ff91d.png)

**Platform:**
PC ST4

**Fix**
I did figure out how to fix it, but I don't know if it is a difference between ST3 -> ST4, or if is something else in the file itself, or if I broke other things.  By moving the second capture up to the scope it seems to have worked.

    # [-] Checkbox
    - match: (\[[ ]\])\s?
      scope: string orgmode.checkbox
    - match: (\[[xX]\])\s?
      scope: keyword orgmode.checkbox.checked
      # scope: orgmode.checkbox.checked
      # captures: 
      #   1: string
      #   2: keyword orgmode.checkbox.checked 
    - match: (\[[\-]\])\s?
      scope: constant.other orgmode.checkbox.blocked
      # scope: orgmode.checkbox.blocked
      # captures:
      #   1: string
      #   2: constant.other orgmode.checkbox.blocked
      # [#/#] Checkbox summary
    - match: (\[\d*[/%]\d*\])
      scope: string orgmode.checkbox.summary

**Comment by taylorh140** [comment]
Where do you put this? I'm very confused.

**Comment by jeffrey-hicks** [comment]
I forgot to mention, this is a syntax file.  What I did was copy the syntax file out of the org extended package, modify the section I show above, and then save it as a new syntax file in the Packages/User folder.  Then I set the modified syntax file as the default for .org files.

**Comment by ihdavids** [comment]
I actually prefer not to have the entire box colored, just the X.
You could also just add a different scope to the first capture here and modify your color scheme to color the box, and have it fall back on string like it is doing. That would probably be my preferred approach, let people decide what they prefer but default with the behaviour I run with personally. 

:)
