### ISSUE TITLE
Possible issues on Apple Silicon?

### ISSUE THREAD

**Issue by rcherny** [ihdavids/orgextended#61]
**Describe the bug**

First I want to say I'm excited to get using this. Thanks for all the hard work.

I am on an M1 Mac and concerned the package may not be working correctly. I haven't gotten real far with testing it out, but the first sign I had was that images only sometimes showed. To look into this, I opened the internal console and saw a number of errors related to the architecture and Regex.

**Platform:**

- M1 MacBook Pro
- macOS 12.3

**Sublime debug console output**

`ImportError: dlopen(/Users/robert/Library/Application Support/Sublime Text 3/Packages/regex/st3_osx/_regex.so, 0x0002): tried: '/Users/robert/Library/Application Support/Sublime Text 3/Packages/regex/st3_osx/_regex.so' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e'))`

There are a lot of these. Since this is a possible fundamental architecture issue, I just wanted to note as much and see if you were aware of anyone using an M1/arm Mac and if this is a solvable problem.

If you're unaware or the problem is potentially unique to me, I can try digging more, but I was curious what, if anything, you knew. I can also provide more context and more specific `Traceback (most recent call last)` stacks, etc.

I'm a developer, but don't know much about Python, to be honest.

Thanks again for all the hard work on this. Obviously a labor of love or you wouldn't be doing it.

**Comment by ihdavids** [comment]
I am unaware of any issues but I do not own an M1. 
I am sorry your are experiencing problems.
