### ISSUE TITLE
<< dedicated target  ..

### ISSUE THREAD

**Issue by flintforge** [ihdavids/orgextended#62]
First, thanks for making this package and helping greatly to enlarge the org community

**Describe the bug**

The double less-than sign, << opens a dedicated target
following text gets highlighted

**To Reproduce**
simply type << somewhere
where text follows

**Expected behavior**
- dedicated target should be declared when closed <<.*>>
- shouldn't span over multiple lines

**Platform:**
- ST4, org extended 1.2.43

**Comment by ihdavids** [comment]
You are looking for a snippet to do this for you?
Or is it doing something degenerate here? I am not sure I understand?

**Comment by flintforge** [comment]
An org document containing these characters "<<" in a paragraph makes the document, yes, degenerate.
This does not happen when opening links "[[" for instance.
The highlight occurs when the expression is closed. e.g "]]" or ">>" in this case.

**Comment by ihdavids** [comment]
Ah, I see. 
I will see if I can come up with a fix.

**Comment by ihdavids** [comment]
This should be fixed in 1.2.45 which is pushed but waiting to get picked up by package control.
