### ISSUE TITLE
@mermaid-js/mermaid-cli upcoming entry-point change

### ISSUE THREAD

**Issue by aloisklink** [ihdavids/orgextended#65]
Hi maintainers of `ihdavids/orgextended`,

A future release of [@mermaid-js/mermaid-cli](https://github.com/mermaid-js/mermaid-cli) (most likely the next 9.1.6 release) will change the program entry-point.

You'll probably need to change
https://github.com/ihdavids/orgextended/blob/112c995d7d6db3971f4a577228c8e9c4325f64bd/orgsrc/mermaid.py#L32

to

```python
	commandLine = ["node", basedir + "/../@mermaid-js/mermaid-cli/src/cli.js", "-i", cmd.filename, "-o", destFile]
```

I had a quick look at your code, and I'm pretty sure the following will work too, on both the old version and the future version, as the `"mmdc"` executable should automatically point to the new location after the update.

```python
	commandLine = [mmdc, "-i", cmd.filename, "-o", destFile]
```

Apologies for this breaking change. Unfortunately, we had to change the entry-point to upgrade from the old CJS JavaScript module system to the new ESM JavaScript module system.

For more information, see https://github.com/mermaid-js/mermaid-cli/pull/350

**Comment by ihdavids** [comment]
Thank you. This is the first time I have ever had a heads up like this. Really appreciate it.
I will endeavor to try to adapt my support when I can.

**Comment by aloisklink** [comment]
> Thank you. This is the first time I have ever had a heads up like this. Really appreciate it. I will endeavor to try to adapt my support when I can.

No worries :smiley: 

Normally in JavaScript projects, people try to keep breaking changes to the next MAJOR.0.0 release.

However, when we searched GitHub, we only found a few projects (like your's) that might be affected, we thought it'd be fine to do instead do a 0.0.PATCH release, as long as we notified the projects it might potentially break!

**Comment by ihdavids** [comment]
This should be in 1.2.53 of OrgExtended.
Thanks for finding this.
