### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Stuk** [ihdavids/orgextended#67]
Hi! Recently found this extension and really enjoying it, thank you!

I have just run into the bug fixed in https://github.com/ihdavids/orgextended/commit/f10038bd893054384de7f5524ddbacc0ba3f47d9 and was wondering if you could release a new version with this change?

**Comment by ihdavids** [comment]
For sure.
Glad you are enjoying it.

**Comment by ihdavids** [comment]
1.2.51 was cut tonight.
Hopefully it solves your issue.

**Comment by Stuk** [comment]
Yes it did, thank you!
