### ISSUE TITLE
Clocking Out Does Not Work

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [ihdavids/orgextended#7]
I'm assuming that clocking in and out on a taskis a matter of `alt+o, c, i` to clock in, and similarly, `alt+o, c, o` to clock out.
Clocking in seems to work ok, but when I try to clock out, the clock entry is just removed. See the attached video where I use these key combinations to try and clock out

https://user-images.githubusercontent.com/1378483/107827008-35c3c600-6d86-11eb-8d34-34ef02ecb628.mp4

**Comment by ihdavids** [comment]
Heh, this is actually something silly on my part. I will make this configurable. I don't like clock values that are less than a minute. So I nuke them if I clock out of something that didn't take a reasonable amount of time. I will make this a configurable option.

**Comment by ihdavids** [comment]
This will be in 1.0.8. The option is poorly named: 
    "clockingSubMinuteClocks": true,

**Comment by ihdavids** [comment]
New option added in 1.0.8 which has just been pushed
