### ISSUE TITLE
Archive all DONE tasks?

### ISSUE THREAD

**Issue by Stuk** [ihdavids/orgextended#72]
Is there a way to archive all tasks with a DONE status?

Either built in or a way to code this up myself. Thanks!

**Comment by ihdavids** [comment]
The command does not exist at the moment.
It could be added if you want to and i will happily pull a PR.

**Comment by ihdavids** [comment]
I have added a simplistic version of this command in 1.2.55 which should be released relatively soon.

**Comment by ihdavids** [comment]
The command will operate on the current file, iterate through all todo's with a DONE status and call the archive command. It's not really that flexible at the moment.

If you want something more flexible please let me know.
