### ISSUE TITLE
Agenda view: day view bug

### ISSUE THREAD

**Issue by meljoann** [ihdavids/orgextended#73]
Hi, first thanks for this brilliant package!

**Describe the bug**
When I open Agenda View it shows the following under Day view:

- All past & future TODO and DONE tasks, in order of scheduled time of day, earliest to latest.
- Underneath that, all past & future TODO and DONE tasks, with no scheduled time.

This happens when today is selected in the calendar, or any other day.

**To Reproduce**
Open agenda view, with alt+o o a

**Expected behavior**
Expected behaviour would be just to show TODO tasks for the currently selected day?

**Platform:**
- Windows 10, Sublime Text Build 4143
- Org files are on iCloud

**Sublime debug console output**
DPI mode: per-monitor v2
startup, version: 4143 windows x64 channel: stable
executable: /C/Program Files/Sublime Text/sublime_text.exe
application: /C/Program Files/Sublime Text
working dir: /C/Program Files/Sublime Text
packages path: /C/Users/M Ryan/AppData/Roaming/Sublime Text/Packages
state path: /C/Users/M Ryan/AppData/Roaming/Sublime Text/Local
zip path: /C/Program Files/Sublime Text/Packages
zip path: /C/Users/M Ryan/AppData/Roaming/Sublime Text/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.228138
startup time: 0.340139
first paint time: 0.409139
git: using configuration from C:\Program Files\Git\cmd\git.exe
git: ignoring working dir /C/Users/M Ryan
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading python 3.3 plugin 0_package_control_loader.00-package_control
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading python 3.3 plugin 0_package_control_loader.50-dateutil
reloading plugin Default.symbol
reloading python 3.3 plugin 0_package_control_loader.50-pathlib
reloading python 3.3 plugin 0_package_control_loader.50-pyyaml
reloading python 3.3 plugin 0_package_control_loader.50-regex
reloading python 3.3 plugin 0_package_control_loader.50-requests
reloading python 3.3 plugin OrgExtended.asettings
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading python 3.3 plugin OrgExtended.beancount
reloading python 3.3 plugin OrgExtended.orgagenda
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading python 3.3 plugin OrgExtended.orgbuiltinresources
reloading python 3.3 plugin OrgExtended.orgcapture
reloading python 3.3 plugin OrgExtended.orgcheckbox
reloading python 3.3 plugin OrgExtended.orgclocking
reloading python 3.3 plugin OrgExtended.orgdatepicker
reloading python 3.3 plugin OrgExtended.orgdaypage
reloading python 3.3 plugin OrgExtended.orgdb
reloading python 3.3 plugin OrgExtended.orgduration
reloading python 3.3 plugin OrgExtended.orgdwim
SETTINGS IS NULL? IS THIS BEING CALLED BEFORE PLUGIN START?
reloading python 3.3 plugin OrgExtended.orgdynamicblock
reloading python 3.3 plugin OrgExtended.orgediting
reloading python 3.3 plugin OrgExtended.orgexporter
reloading python 3.3 plugin OrgExtended.orgextended
reloading python 3.3 plugin OrgExtended.orgextension
reloading python 3.3 plugin OrgExtended.orgfolding
reloading python 3.3 plugin OrgExtended.orghtml
reloading python 3.3 plugin OrgExtended.orghtmlexporter
reloading python 3.3 plugin OrgExtended.orginsertselected
reloading python 3.3 plugin OrgExtended.orginternalediting
reloading python 3.3 plugin OrgExtended.orginternalhelpers
reloading python 3.3 plugin OrgExtended.orglatex
reloading python 3.3 plugin OrgExtended.orglinks
reloading python 3.3 plugin OrgExtended.orglist
reloading python 3.3 plugin OrgExtended.orgmouse
reloading python 3.3 plugin OrgExtended.orgnavigation
reloading python 3.3 plugin OrgExtended.orgneovi
reloading python 3.3 plugin OrgExtended.orgnotifications
reloading python 3.3 plugin OrgExtended.orgnumberedlist
reloading python 3.3 plugin OrgExtended.orgpandoc
reloading python 3.3 plugin OrgExtended.orgplist
reloading python 3.3 plugin OrgExtended.orgproperties
reloading python 3.3 plugin OrgExtended.orgreadtheorg
reloading python 3.3 plugin OrgExtended.orgrevealjs
reloading python 3.3 plugin OrgExtended.orgsourceblock
reloading python 3.3 plugin OrgExtended.orgswiper
reloading python 3.3 plugin OrgExtended.orgtableformula
reloading python 3.3 plugin OrgExtended.orgtableplot
reloading python 3.3 plugin OrgExtended.orgtimechart
reloading python 3.3 plugin OrgExtended.orgtrello
Install the Trello Package to add trello support to OrgExtended for SublimeText 
  >> No module named 'Trello'
reloading python 3.3 plugin OrgExtended.orguniqueview
reloading python 3.3 plugin OrgExtended.orgunittests
reloading python 3.3 plugin OrgExtended.orgxmlthemeparser
reloading python 3.3 plugin OrgExtended.packagecon
reloading python 3.3 plugin OrgExtended.pymitter
reloading python 3.3 plugin OrgExtended.simple_eval
reloading python 3.3 plugin Package Control.1_reloader
reloading python 3.3 plugin Package Control.2_bootstrap
reloading python 3.3 plugin Package Control.Package Control
reloading python 3.3 plugin Table Editor.table_base
reloading python 3.3 plugin Table Editor.table_border_syntax
reloading python 3.3 plugin Table Editor.table_emacs_org_mode_syntax
reloading python 3.3 plugin Table Editor.table_lib
reloading python 3.3 plugin Table Editor.table_lib_test
reloading python 3.3 plugin Table Editor.table_line_parser
reloading python 3.3 plugin Table Editor.table_multi_markdown_syntax
reloading python 3.3 plugin Table Editor.table_pandoc_syntax
reloading python 3.3 plugin Table Editor.table_plugin
reloading python 3.3 plugin Table Editor.table_plugin_test
reloading python 3.3 plugin Table Editor.table_re_structured_text_syntax
reloading python 3.3 plugin Table Editor.table_simple_syntax
reloading python 3.3 plugin Table Editor.table_textile_syntax
reloading python 3.3 plugin Table Editor.widechar_support
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2023-05-31 11:44:09, next run at 2023-05-31 12:44:09 or after

**Additional context**
I haven't changed much in the settings. Just set orgDirs, and
{ "firstDayOfWeek": "Monday",
	  "todoStates": ["TODO", "DONE"] }

**Comment by ihdavids** [comment]
Hmmm, that is very odd. I will take a look when I can and see what I can figure out. Not a lot to go on here.

**Comment by meljoann** [comment]
Oh thanks! I'd forgotten to say, I think other people had trouble with the "space in your username" thing so it might be just that borking everything... why did I keep the space lol

**Comment by ihdavids** [comment]
Actually the agenda is configurable. The default configuration has lists of todos but is not setup to filter for just today in the agenda lists. I should probably add options to do that but the defaults lists aren't doing that at all since I tended to want to know which projects didn't have next actions etc. The agenda I built serves as 2 things for me.

1. My agenda
2. My GTD style daily triage list.

For now, I am going to close this but if you have any problems please feel free to open another ticket. (Or push a PR)
