### ISSUE TITLE
Using OrgExtended on Sublime 2

### ISSUE THREAD

**Issue by siemenbaader** [ihdavids/orgextended#74]
Hi, 

this is a (newbie) question, not an actual bug report. This is the only way I could find to get in touch though... Sorry. 

I'm interested in using OrgExtended with SublimeText2. But it seems not possible..? Can I make it work, or would you be willing and able to make this adjustment?

Is there a different place to have this conversation as not to create too much noise? 

thanks
Siemen

**Comment by ihdavids** [comment]
Heya,
I don't have a copy of Sublime Text 2. 
The plugin makes use of several dependencies (dependent plugins) and also pulls some other packages (TableEditor for emacs style table edditing, yeah, I didn't write that part I built off of the great work done by another plugin author and just force you to install his package)

I am not sure the state of package dependencies in sublime text 2. I am guessing you would need to pull them, embed them in the package.

**Comment by ihdavids** [comment]
That said, I don't see why you couldn't make it work, I just don't have the time to help I am afraid. :(
(As much as I would love to help you)

**Comment by siemenbaader** [comment]
Hi, thanks for your response. I just switched to Sublime 3 so my problem is solved. :)
