### ISSUE TITLE
defaultpaths should be sensible on all architectures

### ISSUE THREAD

**Issue by kamisori** [ihdavids/orgextended#76]
**Describe the bug**
I open the settings entry in a fresh package-installed extended org OrgExtended.sublime-settings file, which i cannot edit, only (probably?) overwrite/shadow the values of your predefined settings and paths which point to your user directory of your windows installation. I dont know where to look for eventual errors but i noticed the windowsy paths and was wondering if there was a way to change the default settings to be filled with some system variables? I have no experience with sublime texts packages but i guess there should be ways to do that

**To Reproduce**
1. Preferences
2. Package Settings
3. OrgExtended
4. Settings

**Expected behavior**
the defaultpaths to be sensible on all architectures

**Platform:**
ubuntu x86

** Sublime debug console output**
Ctrl-~ and include the output here. Idk, this does nothing on my machine but i guess it was ctrl+`
or on my keyboard ctrl+@
...:
...
reloading python 3.3 plugin OrgExtended.orgdb
reloading python 3.3 plugin OrgExtended.orgduration
reloading python 3.3 plugin OrgExtended.orgdwim
SETTINGS IS NULL? IS THIS BEING CALLED BEFORE PLUGIN START?
reloading python 3.3 plugin OrgExtended.orgdynamicblock
reloading python 3.3 plugin OrgExtended.orgediting
reloading python 3.3 plugin OrgExtended.orgexporter
...
orgDir path c:/Users/ian/notes does not exist!

**Additional context**
i get that the orgdirs array should be filled in by me, but the default points to "c:\\Users\\ian\\notes" while it could probably point to something like idk, i havent checked the documentation.

but what about these lines?:

    "resolver.jira.url":"http://sandbox.onjira.com/browse/%s",

...

    // Captures go into this file for refiling later.
    "refile": "D:\\Build\\notes\\refile.org",

...

    // For the plantuml source blocks, where is planuml found?
    "plantuml": "D:\\Build\\.imacs\\plantuml.jar",

    "mermaid":      "C:/Users/ihdav/node_modules/.bin/mmdc",

i dont know where to redirect those to on my system

**Comment by ihdavids** [comment]
Yup all of those settings can easily be overriden and is up to you to override. If you would like to provide a set of defaults that work well for your platform, fire me a PR and we can try to get it into the mainline.

**Comment by ihdavids** [comment]
The overrides are standard sublime settings file override. You should be able to select it Settings > Package Settings > Org Extended and that will make a User folder override file for you.
