### ISSUE TITLE
Second-level headers are underlined

### ISSUE THREAD

**Issue by cip123** [ihdavids/orgextended#77]
**Describe the bug**
Second-level headers are underlined

**To Reproduce**
1. Create an org file
2. create a first-level header `*`
3. Press enter
4. go to the beginning of the row, delete the empty spaces
5. create a second-level header `**`

**Expected behavior**
I shouldn't see the whole second row underlined

**Screenshots**

**Platform:**
- Linux ST4

![Screenshot from 2023-10-02 14-55-31](https://github.com/ihdavids/orgextended/assets/1565500/9ece1314-0cc1-4309-a722-03179b718a3d)

**Comment by ihdavids** [comment]
This is a product of your theme. The default theme has headline 2 defined to be underlined. 
There is a theme generator that can take and extend your current theme and should allow you to style the headlines as you would like.
