### ISSUE TITLE
FR: Syntax format active date time like SCHEDULED or DEADLINE datetime stamp

### ISSUE THREAD

**Issue by schultzter** [ihdavids/orgextended#78]
**Describe the bug**
Not all date time datetime stamps are formatted so they stand out from the rest of the text - only DEADLINE and SCHEDULED are formatted. 

**To Reproduce**
Create an org-mode document with the content:
``` org
Test

* Testing stuff
  DEADLINE: <2023-11-21 Tue 15:01-15:15>

  SCHEDULED: <2023-11-22 Wed 09:00-10:00>

  <2023-11-23 Thu 11:00-11:30> 
  This is some regular paragraph text the is the same colour as the active date time above.
```

**Expected behavior**
SCHEDULED and DEADLINE datetime stamps are syntax formatted differently so they stand out and are easy to see but simple active datetime stamps are not formatted so they blend in with the rest of the text. 

**Screenshots**
Here's what it looks like today:
![image](https://github.com/ihdavids/orgextended/assets/30871/8fd6c129-7605-4dc1-863b-0eb4f5757992)

**Platform:**
- Win 11

** Sublime debug console output**
- NA

**Additional context**

**Comment by ihdavids** [comment]
I wouldn't call this a bug.
I think I found it was a bit problematic highlighting active timestamps at one point so I removed the generic highlight.
But you can add it back:

In the orgextended.sublime-syntax just add a line probably matchine ^\s*{{datetime}}\s*$
and then add the markup.italic and orgmode.datetime tags so it gets highlighted like you expect.

    - match: "(SCHEDULED:)\\s+({{datetime}})"
      captures:
        1: keyword orgmode.statekeyword
        2: markup.italic orgmode.datetime
      scope: orgmode.scheduled

**Comment by ihdavids** [comment]
If you run with it for a while and aren't experiencing any issues fire me a PR and we can see about getting that into the mainline for you.
