### ISSUE TITLE
Generated color schemas (partially) use camelCase instead of snake_case

### ISSUE THREAD

**Issue by tim3z** [ihdavids/orgextended#83]
**To Reproduce**

1. Follow the instructions from https://github.com/ihdavids/orgextended_docs/blob/master/setup.org#color-scheme-generator
2. Wonder why the highlighted line looks so different in org files
3. Check generated org color schema file
4. Notice that it sets `"lineHighlight"` in the `"globals"` section instead of `"line_highlight" which sublime would expect for it to apply (also applies to other keys made up of more than one word)

**Expected behavior**
Generated color schema uses the keys that set the respective colors in sublime.

**Platform:**
Mac ST4

Not critical at all. Just took me a while to figure out whats going on, so this issue might spare someone else the surprise. I briefly checked if I could implement a fix but I failed to understand the color schema generator within a reasonable timeframe. Also it's easy to fix manually. Just surprising 🤷‍♂️

**Comment by ihdavids** [comment]
Thanks, I have been stuck in VsCode land for a while. 
Over there I implemented a bunch of the functionality in a silly external server. 

I am back in sublime again and it looks like I have my work cut out for me in cleaning things up. Lots of little issues.

**Comment by LloydLore** [comment]
Welcome back @ihdavids , actually I also encounter the same issue these days, I tried to find the command `org_create_color_scheme_from_active` location, but failed, I believe that this issue is related to this command...

**Comment by ihdavids** [comment]
Seems that camelCase is comming from the parse color scheme itself. I am not sure why. So, I detect it, and output a line_highlight if not present to compensate. 

Fix should be in 1.2.54
