### ISSUE TITLE
Cookies are wrongly calculated in lists with checkboxes

### ISSUE THREAD

**Issue by Nicryc** [ihdavids/orgextended#84]
**Describe the bug**
Cookies are wrongly calculated in lists with checkboxes. In the following example, we can see that cookies add up all the checkboxes below them that are on the same level until the end of the list regardless of relations (nephew or children).

```org
* Test [2/6]
  - First [2/6]
    - [X] A
  - Second [1/5]
    - [-] B [2/3]
      - [ ] Alpha
      - [X] Beta
      - [X] Gamma
    - [ ] C
  - Third [1/3]
    - [X] D [2/2]
      - [X] Delta
      - [X] Epsilon
    - [ ] E
    - [ ] F
```

Additionally, cookie in heading is adding up too although its direct children don't have checkboxes.

**To Reproduce**
1. Create a new `.org` file
2. Create a list with some children, checkboxes and cookies (you can test with the example above)
3. Recalc using `alt+o, c, c` keybinding

**Expected behavior**
Cookies should only count direct children checkboxes (not nephew).
On Emacs it does:
```org
* Test [0/0]
  - First [1/1]
    - [X] A
  - Second [0/2]
    - [-] B [2/3]
      - [ ] Alpha
      - [X] Beta
      - [X] Gamma
    - [ ] C
  - Third [1/3]
    - [X] D [2/2]
      - [X] Delta
      - [X] Epsilon
    - [ ] E
    - [ ] F
```
Note the heading cookie which displays `[0/0]`

**Platform:**
- Windows 10 Sublime Text 4169

**Comment by ihdavids** [comment]
The list code couldn't handle alternative list types like that. I have improved it a bit, hopefully.
Should be shipped in 1.2.54
