### ISSUE TITLE
Syntax highlight custom Todo States (todoStates) 

### ISSUE THREAD

**Issue by schultzter** [ihdavids/orgextended#87]
**Describe the bug**
I prefer four letter Todo States (ex.: TODO, NEXT, DONE, CNCL, MEET, NOTE) but when I customize them the custom ones do not get syntax highlighted like the default ones. 

**To Reproduce**
1. Change the values of todoStates setting, ex.: "todoStates": ["TODO","NEXT", "WAIT","|", "CNCL", "DONE","MEET","NOTE"],
2. Use new values in an org file

**Expected behavior**
Custom Todo States are syntax highlighted just like default ones.

**Screenshots**
![image](https://github.com/ihdavids/orgextended/assets/30871/97b21a25-2b8f-4514-88aa-72d4e3c4a9ce)

**Platform:**
- Win 11

** Sublime debug console output**
N/a

**Additional context**
N/a

**Comment by ihdavids** [comment]
I would love to add that feature but right now I am relying on the current sublime color scheme and org grammar.
You CAN augment your current color scheme to highlight those states but they are all lumped into the same scope.

**Comment by ihdavids** [comment]
Even though the state is not colored it is still treated as a state by the system.
But if you want it to be highlighted you can extend:

  state: (TODO)|(BLOCKED)|(WAITING)|(CANCELLED)|(DONE)|(MEETING)|(PHONE)|(NOTE)|(FLAG)|(CLEANUP)|(IN-PROGRESS)|(DOING)|(NEXT)|(REASSIGNED)|(FIXED)

In orgextended.sublime-syntax and then extend the capture groups with your states and then run 
OrgCreateColorSchemeFromActive command on a buffer with a color scheme you want to use, then go to your user folder and extend the generated color scheme to include the scopes in your tag you can color code them as you would like.
