### ISSUE TITLE
Org Sort doesn't seem to do anything, no docs!

### ISSUE THREAD

**Issue by schultzter** [ihdavids/orgextended#88]
**Describe the bug**
When I launch **Org Sort List** it doesn't do anything! And I couldn't find anything in the docs to explain what it should do. 

**To Reproduce**
1. Put the cursor in a header
2. Select Org Sort List from the command palette 
3. Nothing happens!

**Expected behavior**
Like emacs I expected to be presented with a choice of how I want my items sorted 

**Screenshots**
![image](https://github.com/ihdavids/orgextended/assets/30871/7458dfab-83d6-4889-93dc-632f73baa221)

**Platform:**
PC Win 11 ST4

** Sublime debug console output**
None

**Additional context**
None

**Comment by schultzter** [comment]
See this section of the Org Manual: https://www.gnu.org/software/emacs/manual/html_node/org/Structure-Editing.html#index-C_002dc-_005e

> C-c ^ (org-sort)
> Sort same-level entries. When there is an active region, all entries in the region are sorted. Otherwise the children of the current headline are sorted. The command prompts for the sorting method, which can be alphabetically, numerically, by time—first timestamp with active preferred, creation time, scheduled time, deadline time—by priority, by TODO keyword—in the sequence the keywords have been defined in the setup—or by the value of a property. Reverse sorting is possible as well. You can also supply your own function to extract the sorting key. With a C-u prefix, sorting is case-sensitive.

**Comment by ihdavids** [comment]
There are some docs now!
https://github.com/ihdavids/orgextended_docs/blob/master/lists.org#sorting-lists

Thanks for using it. Sadly that command only works on lists not headings.
Even more annoying is this is not org mode. I can't even begin to approach that system with the many devs contributing to its awesomeness. This is just my personal little immitation.

If you would like to expand the command to work with headings and be a little more DWIM I would certainly appreciate the help.
