### ISSUE TITLE
Cannot Unhide Link URL

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [ihdavids/orgextended#9]
Using Tab will hide a link url, but will not unhide it

1. Make a heading
2. Under the heading make a link (I was using the following YouTube link https://www.youtube.com/watch?v=vc1E5CfRfos
3. Hit Home to go to the start of the line, then hit tab to hide the url. The url hides correctly
4. Hit tab again. The url does not unhide.

At the end of this video I'm repeatedly hitting tab

https://user-images.githubusercontent.com/1378483/107847130-2f1a6a80-6de9-11eb-9073-ba04abb39bf9.mp4

**Comment by ihdavids** [comment]
That is actually intentional.
If you move your cursor through the link it will expand.
This is something I could make configurable if you want, that said, this is an attempt to (poorly) imitate org mode in emacs. The link text is not important... only the ability to follow it and or store it.

**Comment by ihdavids** [comment]
https://m.youtube.com/watch?v=BRqjaN4-gGQ

In that video you can see the behaviour. Org mode turns the actual link into a clean hyperlink.

I dont quite support the full link syntax but I have some of it. I am also working on the link manipulation commands... 

I have a create link in clipboard command but not all the other fancy commands. Note this thing will probably never be as powerful as the full emacs org mode. That said, i am happy to work on things that are useful to you as long as I can make time.

**Comment by ihdavids** [comment]
I have asked a couple of times for a more narrowing like extension to sublime text in st4 on the forums and discord channel. I love being able to narrow the view to a subtree as if that was all that was in the document. I also love hiding the decoration for a link and leaving JUST the legible bits so your document is much cleaner to read.

**Comment by ihdavids** [comment]
Folding works... its just less clean and a bit more janky.

That said, if you dont like it I can make that configurable.

**Comment by Anti-Distinctlyminty** [comment]
As I new user, it seems I'm having to make some assumptions about the way things are meant to work, so apologies for that.

> If you move your cursor through the link it will expand.

This does not seem to work for me, as you can see here

https://user-images.githubusercontent.com/1378483/107861059-80efde80-6e43-11eb-9dd7-45138c776d96.mp4

**Comment by ihdavids** [comment]
Yeah, that is definitely broken. I will take a look. 
Sorry about that.

**Comment by ihdavids** [comment]
This is fixed in 1.0.9. ( I just pushed 1.0.9 )
I have made tab always toggle the link. 
NOTE that links are aggressively refolded, much like property drawers.

**Comment by ihdavids** [comment]
1.0.9 also comes with some new selection options.
